//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1318.
// 
#pragma warning disable 1591

namespace SilverlightWebServiceClient.facebookProxy {
    using System;
    
    
    /// <remarks/>
    public partial class SilverlightService : System.Windows.Browser.Net.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SilverlightService() {
            this.Url = "http://facebook.claritycon.com/SilverlightService.asmx";
        }
        
        /// <remarks/>
        public UserJSON[] GetFriends(string api, string secret, string session, string userid) {
            object[] results = this.Invoke("GetFriends", new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter[] {
                        new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter("api", api),
                        new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter("secret", secret),
                        new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter("session", session),
                        new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter("userid", userid)}, typeof(UserJSON[]));
            return ((UserJSON[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetFriends(string api, string secret, string session, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFriends", new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter[] {
                        new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter("api", api),
                        new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter("secret", secret),
                        new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter("session", session),
                        new System.Windows.Browser.Net.SoapHttpClientProtocol.ServiceParameter("userid", userid)}, typeof(UserJSON[]), callback, asyncState);
        }
        
        /// <remarks/>
        public UserJSON[] EndGetFriends(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserJSON[])(results[0]));
        }
    }
    
    /// <remarks/>
    public partial class UserJSON {
        
        private string userIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string nameField;
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private System.DateTime profileUpdateDateField;
        
        private string musicField;
        
        private string activitiesField;
        
        private string interestsField;
        
        private string tVShowsField;
        
        private string moviesField;
        
        private string booksField;
        
        private string quotesField;
        
        private string aboutMeField;
        
        private string pictureUrlField;
        
        private string significantOtherIdField;
        
        private string religionField;
        
        private int notesCountField;
        
        private int wallCountField;
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ProfileUpdateDate {
            get {
                return this.profileUpdateDateField;
            }
            set {
                this.profileUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        public string Music {
            get {
                return this.musicField;
            }
            set {
                this.musicField = value;
            }
        }
        
        /// <remarks/>
        public string Activities {
            get {
                return this.activitiesField;
            }
            set {
                this.activitiesField = value;
            }
        }
        
        /// <remarks/>
        public string Interests {
            get {
                return this.interestsField;
            }
            set {
                this.interestsField = value;
            }
        }
        
        /// <remarks/>
        public string TVShows {
            get {
                return this.tVShowsField;
            }
            set {
                this.tVShowsField = value;
            }
        }
        
        /// <remarks/>
        public string Movies {
            get {
                return this.moviesField;
            }
            set {
                this.moviesField = value;
            }
        }
        
        /// <remarks/>
        public string Books {
            get {
                return this.booksField;
            }
            set {
                this.booksField = value;
            }
        }
        
        /// <remarks/>
        public string Quotes {
            get {
                return this.quotesField;
            }
            set {
                this.quotesField = value;
            }
        }
        
        /// <remarks/>
        public string AboutMe {
            get {
                return this.aboutMeField;
            }
            set {
                this.aboutMeField = value;
            }
        }
        
        /// <remarks/>
        public string PictureUrl {
            get {
                return this.pictureUrlField;
            }
            set {
                this.pictureUrlField = value;
            }
        }
        
        /// <remarks/>
        public string SignificantOtherId {
            get {
                return this.significantOtherIdField;
            }
            set {
                this.significantOtherIdField = value;
            }
        }
        
        /// <remarks/>
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public int NotesCount {
            get {
                return this.notesCountField;
            }
            set {
                this.notesCountField = value;
            }
        }
        
        /// <remarks/>
        public int WallCount {
            get {
                return this.wallCountField;
            }
            set {
                this.wallCountField = value;
            }
        }
    }
}

#pragma warning restore 1591